name: Python Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup Test Video
      run: |
        # Cria um arquivo de vídeo fake para o teste de integração não falhar
        touch video_teste.mp4

    - name: Run API and Tests
      run: |
        # Adiciona a raiz do projeto ao path para o Python achar as pastas swagger e API
        export PYTHONPATH=$PYTHONPATH:$(pwd)

        # Inicia a API
        python API/app.py &

        # Espera a API e o Swagger subirem
        sleep 10

        # Roda os testes
        python -m unittest discover -s API/__tests__ -p 'test_*.py'
