name: Python Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # Versão ideal para evitar erros de compatibilidade

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx ffmpeg # Necessário para OpenCV e gerar vídeo

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Dummy Video for Testing
      run: |
        # Gera um vídeo real de 1 segundo (cor preta, 1fps) para o OpenCV conseguir ler
        ffmpeg -f lavfi -i color=c=black:s=640x480:d=1 -vf "fps=1" video_teste.mp4

    - name: Run API and Tests
      run: |
        # Garante que as pastas API e core sejam visíveis
        export PYTHONPATH=$PYTHONPATH:$(pwd)

        # Inicia a API em background
        python API/app.py &

        # Espera a API subir (10s é seguro)
        sleep 10

        # Roda os testes usando o módulo unittest
        python -m unittest discover -s API/__tests__ -p 'test_*.py'
